{
	"version": 1536671147,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/bg-sheet0.png",
		"images/box-sheet0.png",
		"images/player-sheet0.png",
		"images/arrowr-sheet0.png",
		"images/arrowr-sheet1.png",
		"images/sprite-sheet0.png",
		"images/objct-sheet0.png",
		"images/tap-sheet0.png",
		"images/arrowstart-sheet0.png",
		"media/woosh sound effect (128  kbps) (greenmp3.com).m4a",
		"media/woosh sound effect (128  kbps) (greenmp3.com).ogg",
		"media/big_gun_shots_close (mp3cut.net).m4a",
		"media/big_gun_shots_close (mp3cut.net).ogg",
		"media/hand_claps_close (mp3cut.net).m4a",
		"media/hand_claps_close (mp3cut.net).ogg",
		"media/1.m4a",
		"media/bg.m4a",
		"media/bg.ogg",
		"media/future_city_funk.m4a",
		"media/future_city_funk.ogg",
		"media/controlled_distress.m4a",
		"media/controlled_distress.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}